Repository KILTprotocol/sdk-js, pull requests merged in 2020-07, with the labels that each got.

#275 Feat: Debug mode and modify logLevel
  src/config/ConfigLog.spec.ts
  src/config/ConfigLog.ts
Labels: ✨ new feature

#278 test: attested claim coverage
  src/attestation/Attestation.spec.ts
  src/attestation/Attestation.ts
  src/attestedclaim/AttestedClaim.spec.ts
Labels: 🚨 tests

#286 fix: decoding types
  package.json
  src/actor/Attester.spec.ts
  src/actor/Claimer.spec.ts
  src/actor/Verifier.spec.ts
  src/attestation/Attestation.chain.ts
  src/attestation/Attestation.spec.ts
  src/balance/Balance.spec.ts
  src/blockchain/Blockchain.spec.ts
  src/blockchainApiConnection/BlockchainApiConnection.ts
  src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
  src/blockchainApiConnection/__mocks__/BlockchainQuery.ts
  src/delegation/Delegation.chain.ts
  src/delegation/Delegation.spec.ts
  src/delegation/DelegationDecoder.ts
  src/delegation/DelegationNode.spec.ts
  src/delegation/DelegationRootNode.spec.ts
  src/did/Did.spec.ts
  src/did/Did.utils.ts
  src/identity/PublicIdentity.spec.ts
  yarn.lock
Labels: ♻️ refactoring, 🐛 bug

#281 test: add privacy enhanced attestation to CI
  src/__integrationtests__/AttestationPE.spec.ts
  src/__integrationtests__/utils.ts
Labels: 💚 low, 🚨 tests

#283 test: improve actor coverage
  src/actor/Attester.spec.ts
  src/actor/Claimer.spec.ts
  src/actor/Verifier.spec.ts
  src/actor/Verifier.ts
  src/errorhandling/SDKErrors.ts
Labels: 💚 low, 🚨 tests

#289 chore: add dispatch event to workflow
  .github/workflows/devpackpublish.yml
Labels: 🚨 tests

#291 docs: update to Substrate 2.0 compliance
  .github/workflows/tests.yml
  README.md
  docs/development-setup.md
  docs/getting-started.md
  docs/getting-started.ts
Labels: :memo: documentation, 🚨 tests

#295 chore: upgrade dependencies
  package.json
  src/attestation/Attestation.ts
  src/ctype/CType.ts
  yarn.lock
Labels: dependencies
