Repository KILTprotocol/sdk-js, pull requests merged in 2020-06, with the labels that each got.

#252 chore: fixed spelling issues
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/Delegation.spec.ts
  src/attestation/Attestation.spec.ts
  src/attestation/Attestation.utils.ts
  src/attestedclaim/AttestedClaim.spec.ts
  src/attestedclaim/AttestedClaim.ts
  src/attestedclaim/AttestedClaim.utils.ts
  src/claim/Claim.utils.ts
  src/ctype/CType.spec.ts
  src/ctype/CType.utils.ts
  src/ctype/CTypeMetadata.ts
  src/delegation/DelegationNode.utils.ts
  src/did/Did.spec.ts
  src/did/Did.ts
  src/errorhandling/ExtrinsicError.ts
  src/identity/PublicIdentity.spec.ts
  src/quote/Quote.spec.ts
  src/quote/Quote.utils.ts
  src/requestforattestation/RequestForAttestation.spec.ts
  src/requestforattestation/RequestForAttestation.ts
  src/requestforattestation/RequestForAttestation.utils.ts
Labels: ♻️ refactoring

#258 feat: anonymous credentials - portablegabi
  .github/workflows/tests.yml
  .gitignore
  .nvmrc
  docs/example.ts
  package.json
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Balance.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/Delegation.spec.ts
  src/__integrationtests__/Did.spec.ts
  src/__integrationtests__/utils.ts
  src/actor/Attester.spec.ts
  src/actor/Attester.ts
  src/actor/Claimer.spec.ts
  src/actor/Claimer.ts
  src/actor/Verifier.spec.ts
  src/actor/Verifier.ts
  src/attestation/Attestation.spec.ts
  src/attestation/Attestation.ts
  src/attestedclaim/AttestedClaim.spec.ts
  src/attestedclaim/AttestedClaim.ts
  src/attestedclaim/AttestedClaim.utils.ts
  src/attesteridentity/AttesterIdentity.ts
  src/attesteridentity/PublicAttesterIdentity.ts
  src/balance/Balance.spec.ts
  src/blockchain/Blockchain.ts
  src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
  src/claim/Claim.spec.ts
  src/credential/Credential.spec.ts
  src/credential/Credential.ts
  src/crypto/Crypto.spec.ts
  src/ctype/CType.spec.ts
  src/ctype/CType.ts
  src/ctype/CTypeMetadata.spec.ts
  src/delegation/Delegation.spec.ts
  src/delegation/DelegationNode.spec.ts
  src/delegation/DelegationNode.ts
  src/delegation/DelegationRootNode.spec.ts
  src/delegation/DelegationRootNode.ts
  src/did/Did.spec.ts
  src/did/Did.ts
  src/errorhandling/ErrorHandler.ts
  src/identity/Identity.spec.ts
  src/identity/Identity.ts
  src/identity/PublicIdentity.ts
  src/index.ts
  src/messaging/Message.spec.ts
  src/messaging/Message.ts
  src/quote/Quote.spec.ts
  src/quote/Quote.ts
  src/requestforattestation/RequestForAttestation.spec.ts
  src/requestforattestation/RequestForAttestation.ts
  src/requestforattestation/RequestForAttestation.utils.ts
  src/test/constants.ts
  src/types/Attestation.ts
  src/types/Credential.ts
  src/types/PublicAttesterIdentity.ts
  src/types/RequestForAttestation.ts
  typedoc.js
  yarn.lock
Labels: ✨ new feature

#238 refactor: introduces index files and use them
  src/actor/Attester.ts
  src/actor/Claimer.spec.ts
  src/actor/Claimer.ts
  src/actor/Verifier.spec.ts
  src/actor/Verifier.ts
  src/actor/index.ts
  src/attestation/index.ts
  src/attestedclaim/AttestedClaim.spec.ts
  src/attestedclaim/index.ts
  src/balance/index.ts
  src/blockchain/index.ts
  src/claim/index.ts
  src/config/index.ts
  src/credential/index.ts
  src/ctype/index.ts
  src/delegation/index.ts
  src/did/index.ts
  src/errorhandling/index.ts
  src/identity/AttesterIdentity.ts
  src/identity/Identity.spec.ts
  src/identity/PublicAttesterIdentity.ts
  src/identity/index.ts
  src/index.ts
  src/kilt/index.ts
  src/messaging/index.ts
  src/quote/index.ts
  src/requestforattestation/RequestForAttestation.spec.ts
  src/requestforattestation/index.ts
  src/util/index.ts
Labels: ♻️ refactoring

#260 refactor: use generics on chain queries
  jest.config.js
  package.json
  src/__integrationtests__/Attestation.spec.ts
  src/actor/Attester.spec.ts
  src/attestation/Attestation.chain.ts
  src/attestation/Attestation.spec.ts
  src/blockchain/Blockchain.ts
  src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
  src/ctype/CType.chain.ts
  src/delegation/Delegation.chain.ts
  src/delegation/Delegation.spec.ts
  src/delegation/Delegation.ts
  src/delegation/DelegationDecoder.ts
  src/delegation/DelegationNode.chain.ts
  src/delegation/DelegationNode.spec.ts
  src/delegation/DelegationNode.ts
  src/delegation/DelegationRootNode.chain.ts
  src/delegation/DelegationRootNode.spec.ts
  src/delegation/DelegationRootNode.ts
  src/did/Did.chain.ts
  src/did/Did.spec.ts
  src/did/Did.utils.ts
  src/identity/PublicIdentity.spec.ts
  src/util/Decode.ts
Labels: ♻️ refactoring

#222 feat: Nested CType
  .gitignore
  .npmrc
  package.json
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/utils.ts
  src/actor/Attester.spec.ts
  src/actor/Claimer.spec.ts
  src/actor/Verifier.spec.ts
  src/attestation/Attestation.spec.ts
  src/attestedclaim/AttestedClaim.spec.ts
  src/claim/Claim.spec.ts
  src/claim/Claim.ts
  src/claim/Claim.utils.ts
  src/credential/Credential.spec.ts
  src/ctype/CType.spec.ts
  src/ctype/CType.ts
  src/ctype/CType.utils.spec.ts
  src/ctype/CType.utils.ts
  src/ctype/CTypeMetadata.spec.ts
  src/ctype/CTypeNested.spec.ts
  src/ctype/CTypeSchema.ts
  src/errorhandling/SDKErrors.ts
  src/quote/Quote.spec.ts
  src/requestforattestation/RequestForAttestation.spec.ts
  src/types/CType.ts
  src/types/Claim.ts
Labels: ✨ new feature

#274 feat: publishing to github packages from develop
  .github/workflows/devpackpublish.yml
Labels: ✨ new feature, 🚨 tests
