Repository KILTprotocol/sdk-js, pull requests merged in 2020-05, with the labels that each got.

#261 refactor: chain stats return string types
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Balance.spec.ts
  src/__integrationtests__/ChainConnectivity.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/Delegation.spec.ts
  src/blockchain/Blockchain.spec.ts
  src/blockchain/Blockchain.ts
  src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
Labels: ♻️ refactoring

#256 docs: automated build and deploy
  .github/workflows/docpublish.yml
  .gitignore
  README.md
  docs/contribution-guide.md
  package.json
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Balance.spec.ts
  src/__integrationtests__/ChainConnectivity.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/Delegation.spec.ts
  src/__integrationtests__/Did.spec.ts
  src/__integrationtests__/utils.ts
  src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
  src/delegation/DelegationDecoder.ts
  src/util/UUID.ts
Labels: :memo: documentation

#263 Fix ExtrinsicError array of length 3101
  src/errorhandling/ExtrinsicError.spec.ts
  src/errorhandling/ExtrinsicError.ts
Labels: ♻️ refactoring, 💚 low

#264 Fix: getPublicIdentity should be instanceof PublicIdentity
  src/identity/Identity.spec.ts
  src/identity/Identity.ts
  src/identity/PublicIdentity.ts
Labels: 🐛 bug

#217 Update getting-started.md
  docs/getting-started.md
Labels: :memo: documentation

#254 feat: dockerfile for running integration tests
  .dockerignore
  Dockerfile
  dc.build.node.yml
  docker-compose.yml
  src/__integrationtests__/Attestation.spec.ts
  src/__integrationtests__/Balance.spec.ts
  src/__integrationtests__/ChainConnectivity.spec.ts
  src/__integrationtests__/Ctypes.spec.ts
  src/__integrationtests__/Delegation.spec.ts
  src/__integrationtests__/Did.spec.ts
  src/blockchainApiConnection/BlockchainApiConnection.ts
Labels: ✨ new feature

#267 refactor: messaging
  docs/example.ts
  src/messaging/Message.spec.ts
  src/messaging/Message.ts
Labels: :memo: documentation, ♻️ refactoring
