Repository KILTprotocol/sdk-js, pull requests merged in 2022-03, with the labels that each got.

#481 test against updated dependencies
  .github/workflows/tests-polkadot-deps.yml
  packages/did/src/global.d.ts
  packages/testing/src/mocks/typeRegistry.ts
  yarn.lock
Labels: dependencies

#483 deps: update polkadot dependencies to latest
  .github/workflows/tests.yml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  packages/chain-helpers/package.json
  packages/chain-helpers/src/blockchain/Blockchain.utils.ts
  packages/chain-helpers/src/index.ts
  packages/config/package.json
  packages/config/src/index.ts
  packages/core/package.json
  packages/core/src/__integrationtests__/Ctypes.spec.ts
  packages/core/src/__integrationtests__/Deposit.spec.ts
  packages/core/src/index.ts
  packages/did/package.json
  packages/did/src/index.ts
  packages/messaging/package.json
  packages/messaging/src/index.ts
  packages/sdk-js/package.json
  packages/sdk-js/src/index.ts
  packages/testing/package.json
  packages/testing/src/index.ts
  packages/testing/src/mocks/mockedApi.ts
  packages/testing/src/mocks/mockedApi.utils.ts
  packages/testing/src/mocks/typeRegistry.ts
  packages/types/package.json
  packages/types/src/index.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/vc-export/package.json
  packages/vc-export/src/index.ts
  yarn.lock
Labels: ❤️ high, dependencies

#485 fix: update key types encoding for retro-compatibility
  packages/did/src/Did.chain.ts
  packages/did/src/DidDetails/LightDidDetails.spec.ts
  packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
  packages/types/src/DidDetails.ts
Labels: 🐛 bug

#500 fix: dev release pipeline
  .github/workflows/devpackpublish.yml
Labels: 🐛 bug, automation

#509 fix: add authentication key requirement for didLookup pallet calls
  packages/did/src/DidDetails/FullDidDetails.utils.ts
Labels: 🐛 bug, ❤️ high
